[package]
name = "cddl-lib-wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
core = { path = "../core", package = "cddl-lib-core" }
cbor_event = "2.4.0"
wasm-bindgen = { version = "0.2", features=["serde-serialize"] }
linked-hash-map = "0.5.3"
